process_dir: processed
cache_dir: cache
checkpoint_dir: checkpoint

dataset: dft_3d
# dataset: megnet
# JARVIS: formation_energy_peratom, mbj_bandgap, optb88vdw_bandgap, optb88vdw_total_energy, ehull
# MP: e_form, gap pbe
target: formation_energy_peratom

atom_features: cgcnn

epochs: 10
batch_size: 10
num_workers: 8
weight_decay: 0.0
learning_rate: 1e-3

criterion: mse
optimizer: adamw
scheduler: none

pin_memory: False
write_checkpoint: False
write_predictions: True
store_outputs: False
progress: True
log_tensorboard: True

n_train: 50
n_val: 10
n_test: 10

normalize: False
euclidean: True
cutoff: 4.0
max_neighbors: 16
# infinite_funcs: ["zeta", "zeta", "exp"]
# infinite_params: [0.5, 3.0, 3.0]
infinite_funcs: ["zeta"]
infinite_params: [0.5]
R: 3

model:
  name: potnet
  conv_layers: 3
  rbf_min: -4.0
  rbf_max: 4.0
  # potentials: [-0.801, -0.074, 0.145]
#  potentials: [-0.816, -0.052, 0.149]
  potentials: [-0.816]
  charge_map: False
  transformer: False